title: Ethan's Site
description: Ethan's Site
url: https://ethanrd.github.io
repository: github:ethanrd/ethanrd.github.io
# repository: https://github.com/ethanrd/ethanrd.github.io

markdown: kramdown

exclude:
  - ".gitignore"
  - CNAME
  - README.md