#
# GitHub Actions Workflow for pull request events against the master branch to
# make sure Jekyll still builds. If successful, the resulting html files are
# uploaded as artifacts to make it easier to preview the results of a PR.
#
# For more information on the actions used in this workflow, please see:
#   https://github.com/actions/checkout
#   https://github.com/marketplace/actions/jekyll-builder-for-github-pages
#   https://github.com/actions/upload-artifact
#
name: Check Jekyll Build
on:
  pull_request:
    branches: [ master ]

jobs:
  # Job to test that web page docs build
  build_conventions:
    name: Test the build of web page docs
    runs-on: ubuntu-latest
    steps:
      # Check out PR
      - uses: actions/checkout@v2
      # Create build directory
      - run: mkdir web_pages_build
      # Build HTML from Markdown in repo
      - name: Build Jekyll site.
        uses: meitar/jekyll-builder-for-github-pages-action@v1
        with:
          jekyll_build_opts: --trace