name: Check links
on:
  pull_request:
    branches: [ main ]
#  schedule:
#    - cron: '23 8 * * 1'
  workflow_dispatch:

jobs:
#  markdown-link-check:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@main
#      - uses: gaurav-nelson/github-action-markdown-link-check@v1
#        with:
#          use-verbose-mode: 'yes'

  check_links:
    name: Check Markdown links
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check links
        uses: lycheeverse/lychee-action@v1.0.4
        with:
          args: '*.md' '*.html' --verbose
          debug: true
          # Use different output file path
          #output: /tmp/lychee/out.md
          # Fail action on broken links
          fail: true


      - name: Upload report
        if: ${{ always() }}
        uses: actions/upload-artifact@v1
        with:
          name: Link check report
          path: ./lychee/out.md

#      - name: Create Issue From File
#        uses: peter-evans/create-issue-from-file@v4.0.0
#        with:
#          title: Link Checker Report
#          content-filepath: ./lychee/out.md
#          labels: report, automated issue